name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Allow the job to commit/deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install, build, and upload Astro Pages
        uses: withastro/action@v3
        with:
          node-version: 22

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
